name = "pika_id"
version = "1.1.0"
description = "Gleam implementation of Pika ID"
target = "erlang"

licences = ["Apache-2.0"]

repository = { type = "github", user = "Phineas", repo = "pika" }
internal_modules = [
  "pika_id/internal",
  "pika_id/internal/*",
]
[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_crypto = ">= 1.3.0 and < 2.0.0"
gleam_erlang = ">= 0.25.0 and < 1.0.0"
gleam_otp = ">= 0.10.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
